#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config debug_output on

yabai -m space --layout bsp

yabai -m config window_placement             second_child

yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m config auto_balance                 off

yabai -m config split_ratio                 0.50

yabai -m config mouse_modifier ctrl

yabai -m config mouse_action1 move

yabai -m config mouse_action2 resize

yabai -m config focus_follows_mouse          autofocus

yabai -m config mouse_follows_focus          on


yabai -m config window_shadow                float


yabai -m config window_opacity               on

yabai -m config active_window_opacity        0.98
yabai -m config normal_window_opacity        0.9
yabai -m config window_opacity_duration      0.0

yabai -m config external_bar all:0:0

# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off
# show digital colour meter topmost and on all spaces
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on

echo "yabai configuration loaded.."
